# Production Configuration
# Full-scale settings for live trading research

environment: "production"
log_level: "INFO"

database:
  url: "postgresql://trader:secure_password@localhost:5432/trading_research"
  echo: false
  pool_size: 10
  max_overflow: 20

model:
  # Full dataset
  tickers: ["AAPL", "MSFT", "GOOG", "NVDA", "TSLA", "AMZN", "META"]
  lookback_window: 30
  prediction_horizons: [1, 3, 5, 10]
  target_features: 24
  
  model_params:
    lstm_units_1: 512
    lstm_units_2: 256
    lstm_units_3: 128
    dropout_rate: 0.3
    l2_regularization: 0.003
    directional_alpha: 0.4
    use_attention: true
    dense_layers: [256, 128, 64]
  
  training_params:
    batch_size: 64
    epochs: 100
    learning_rate: 0.0005
    patience: 15
    validation_split: 0.2

backtest:
  transaction_cost: 0.001
  min_position_size: 0.01
  max_position_size: 0.10
  max_drawdown_limit: 0.15
  volatility_target: 0.12
  training_window_days: 252
  rebalance_frequency_days: 5
  walk_forward_window_days: 30

api:
  host: "0.0.0.0"
  port: 8000
  reload: false
  log_level: "INFO"
  model_cache_size: 5
  prediction_timeout: 30